import {
  lucideAlertTriangle,
  lucideArrowLeft,
  lucideBuilding2,
  lucideCheck,
  lucideCheckCircle2,
  lucideChevronDown,
  lucideCircleAlert,
  lucideCopy,
  lucideEye,
  lucideEyeOff,
  lucideInbox,
  lucideInfo,
  lucideKeyRound,
  lucideLoader2,
  lucideLogOut,
  lucideMail,
  lucideMailOpen,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucideMoreVertical,
  lucidePaperclip,
  lucidePlus,
  lucideRefreshCw,
  lucideSearch,
  lucideSettings,
  lucideSmartphone,
  lucideSun,
  lucideTablet,
  lucideTrash2,
  lucideUser,
  lucideX,
} from '@ng-icons/lucide';

/**
 * The app's one and only icon set, registered once in `app.config.ts`. Keep
 * every icon used anywhere in the app listed here so there is a single place
 * that shows the full icon vocabulary.
 */
export const appIcons = {
  lucideAlertTriangle,
  lucideArrowLeft,
  lucideBuilding2,
  lucideCheck,
  lucideCheckCircle2,
  lucideChevronDown,
  lucideCircleAlert,
  lucideCopy,
  lucideEye,
  lucideEyeOff,
  lucideInbox,
  lucideInfo,
  lucideKeyRound,
  lucideLoader2,
  lucideLogOut,
  lucideMail,
  lucideMailOpen,
  lucideMenu,
  lucideMonitor,
  lucideMoon,
  lucideMoreVertical,
  lucidePaperclip,
  lucidePlus,
  lucideRefreshCw,
  lucideSearch,
  lucideSettings,
  lucideSmartphone,
  lucideSun,
  lucideTablet,
  lucideTrash2,
  lucideUser,
  lucideX,
};

/** One of the icon names registered in `appIcons`, for typed `name` inputs on icon-accepting components. */
export type IconName = keyof typeof appIcons;
